name: forecast-academy
channels:
  - conda-forge

dependencies:
  - python=3.11

  # CORE MATH
  - numpy<2.0
  - pandas>=2.0
  - scipy
  - scikit-learn
  - statsmodels

  # NOTEBOOKS & INTERACTIVITY
  - jupyterlab
  - ipywidgets>=8
  - matplotlib
  - seaborn
  - plotly

  # DATA HANDLING
  - pyarrow
  - openpyxl
  - tqdm

  # PERFORMANCE
  - numba
  - llvmlite

  # PIP TOOLING (helps git installs/builds)
  - pip
  - setuptools
  - wheel

  - pip:
      # TSFORGE (from GitHub)
      - git+https://github.com/forecastacademy/tsforge.git

      # NIXTLA STACK
      - statsforecast
      - mlforecast
      - neuralforecast
      - utilsforecast
      - datasetsforecast
      - tsfeatures

      # UTILITIES
      - dtype-diet>=0.0.2
      - gdown
      - holidays
